apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pipeline/00_pvc-tekton-pvc.yaml
  - ./pipeline/01_eventlistener.yaml
  - ./pipeline/02_trigger-template.yaml
  - ./pipeline/03_triggerbinding-app-demo.yaml
  - ./pipeline/04_task-fetch-source.yaml
  - ./pipeline/05_task-pytest.yaml
  - ./pipeline/06_task-s2i.yaml
  - ./pipeline/07_task-sign-image.yaml
  - ./pipeline/08_task-image-check.yaml
  - ./pipeline/09_task-image-scan.yaml
  - ./pipeline/10_task-openshift-client.yaml
  - ./pipeline/11_task-integration-test.yaml
  - ./pipeline/12_task-gitea-set-status.yaml
  - ./pipeline/13_task-kaniko.yaml
  - ./pipeline/99_pipeline-clone-build-push.yaml

  - ./rbac/build-bot.yaml

  - ./tektonchains/tektonchain.yaml
  - ./tektonchains/config.yaml

  #- ./vault/hashicorp.yaml

  - ./gitea/gitea-interceptor-serviceaccount.yaml
  - ./gitea/gitea-interceptor.yaml
  - ./gitea/gitea-route.yaml
  - ./gitea/gitea-server.yaml

  - ./rhacs/central.yaml
  - ./rhacs/create-cluster-init-bundle-job.yaml
  - ./rhacs/create-cluster-init-bundle-sa.yaml
  - ./rhacs/secured-cluster.yaml
